name: Daily GEM Screening with Real Data

on:
  schedule:
    - cron: '30 13 * * 1-5'
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-gem-screening:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Polygon_Integration/requirements.txt
      
      - name: Run GEM Daily Screening
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          cd Polygon_Integration
          python daily_screener.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GEM Screening Bot"
          git add Daily_Operations/CURRENT_UPDATE.md
          git diff --cached --quiet || git commit -m "Daily GEM Screening Update - $(date +'%Y-%m-%d %H:%M')" && git push
